### ISSUE TITLE
Don't store test app in `spec/internal`

### ISSUE THREAD

**Issue by cbeer** [cbeer/engine_cart#23]
Newly generated gemspecs include `spec/**/*` in their `test_files` by default. We should choose another directory (`.test_app`?)  for the generated app.

**Comment by darrenleeweber** [comment]
Migrating commentary from https://github.com/sul-dlss/triannon/issues/206 here, where it adds more value to this issue in the engine cart project.

@cbeer - there is a possible conflict in the engine_cart:regenerate process when it is run using rake at the `triannon` project path, because, at some point during the regeneration, there exists two Gemfile files, one in `triannon/Gemfile` and another in `triannon/spec/internal/Gemfile` and they may conflict with one another, e.g.
```
Bundler could not find compatible versions for gem "tilt":
  In snapshot (Gemfile.lock):
    tilt (= 2.0.1)

  In Gemfile:
    sass-rails (~> 5.0) ruby depends on
      tilt (~> 1.1) ruby

    tilt (>= 0) ruby

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```
(BTW, this error above only appears when `triannon/Gemfile` is NOT hacked to specify a specific tilt dependency, so you have to comment out the `gem 'tilt', '~> 1.1'` to see it.)

When the `triannon/Gemfile.lock` file is removed, then `rake engine_cart:regenerate` does not encounter the error above.  Although I can't prove it right now, it looks like `bundle` is using both `triannon/Gemfile` (`triannon/Gemfile.lock`) and `triannon/spec/internal/Gemfile` (and associated `Gemfile.lock`) when it is called during `engine_cart:regenerate`.  The question is, how can they be isolated, if possible?

**Comment by darrenleeweber** [comment]
@cbeer - might want to note that in triannon, `bundle update` would not upgrade to rails 4.2.3 because the engine_cart app contains `spec/internal/Gemfile`, which had pinned it to 4.2.2.  To get `bundle update` to work properly, try `rm -rf spec/internal; bundle update; rake engine_cart:generate`.  This does not impact travis builds, because `spec/internal` is not in the git repo.
@cbeer - how do we exclude the `triannon/spec/internal/Gemfile` from the `triannon/Gemfile` when using `bundle install` or `bundle update` within the `triannon` project path?

**Comment by darrenleeweber** [comment]
My problems in triannon might be resolved by removing all the code in https://github.com/sul-dlss/triannon/blob/master/Gemfile#L16-L41

**Comment by darrenleeweber** [comment]
It's possibly also related to https://github.com/cbeer/engine_cart/blob/master/lib/generators/engine_cart/install_generator.rb#L59-L64 - so why does engine_cart impose this rather than let rails deps take care of it?

**Comment by darrenleeweber** [comment]
Potential solution is coded in https://github.com/sul-dlss/triannon/commit/c3b51586ba4006aa71a5b0c690e8aa6512a83185, which, if it works OK, might be considered to modify the engine cart install_generator.

**Comment by darrenleeweber** [comment]
@cbeer - see https://github.com/sul-dlss/triannon/compare/c3b51586ba40...afbb99269af0 for something that is worked for triannon on travis.
